adding the github workflow file
Signed-off-by: kjam8024 <meinzerk@hotmail.com>

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -34,3 +34,51 @@ jobs:
       - name: LINT - Run InSpec Check           
         run: inspec check $PROFILE
 
+      # launch a container as the test target
+      - name: DEPLOY - Run a Docker container from nginx
+        run: docker run -dit --name nginx nginx:latest
+
+      # install dependencies on the container so that hardening will work
+      - name: DEPLOY - Install Python for our nginx container
+        run: |
+          docker exec nginx apt-get update -y
+          docker exec nginx apt-get install -y python3
+
+      # fetch the hardening role and requirements
+      - name: HARDEN - Fetch Ansible role
+        run: |
+          git clone --branch docker https://github.com/mitre/ansible-nginx-stigready-hardening.git || true
+          chmod 755 ansible-nginx-stigready-hardening
+
+      - name: HARDEN - Fetch Ansible requirements
+        run: ansible-galaxy install -r ansible-nginx-stigready-hardening/requirements.yml
+
+      # harden!
+      - name: HARDEN - Run Ansible hardening
+        run: ansible-playbook --inventory=nginx, --connection=docker ansible-nginx-stigready-hardening/hardening-playbook.yml
+
+      - name: VALIDATE - Run InSpec
+        # we dont want to stop if our InSpec run finds failures, we want to continue and record the result
+        continue-on-error: true                
+        run: |
+          inspec exec $PROFILE \
+          --input-file=$PROFILE/inputs-linux.yml \
+          --target docker://nginx \
+          --reporter cli json:results/pipeline_run.json
+
+      # attest
+      - name: VALIDATE - Apply an Attestation
+        run: |
+          saf attest apply -i results/pipeline_run.json attestation.json -o results/pipeline_run_attested.json
+
+      # save our results to the pipeline artifacts, even if the InSpec run found failing tests
+      - name: VALIDATE - Save Test Result JSON  
+        uses: actions/upload-artifact@v3
+        with:
+          path: results/pipeline_run_attested.json
+
+      # drop off the data with our dashboard
+      - name: VALIDATE - Upload to Heimdall
+        continue-on-error: true
+        run: |
+          curl -# -s -F data=@results/pipeline_run_attested.json -F "filename=${{ github.actor }}-pipeline-demo-${{ github.sha }}.json" -F "public=true" -F "evaluationTags=${{ github.repository }},${{ github.workflow }}" -H "Authorization: Api-Key ${{ secrets.HEIMDALL_API_KEY }}" "https://heimdall-demo.mitre.org/evaluations"
